/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Status
         * @description Get current system status.
         */
        get: operations["get_status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Test Connections
         * @description Test all external connections.
         */
        get: operations["test_connections_api_connections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Update
         * @description Trigger immediate photo update.
         */
        post: operations["trigger_update_api_update_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clear Display
         * @description Clear the display.
         */
        post: operations["clear_display_api_clear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config
         * @description Get current configuration.
         */
        get: operations["get_config_api_config_get"];
        /**
         * Update Config
         * @description Update in-memory configuration (validation only, not saved).
         */
        put: operations["update_config_api_config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Config
         * @description Save current in-memory configuration to YAML file.
         */
        post: operations["save_config_api_config_save_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/revert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revert Config
         * @description Revert in-memory config to what's on disk.
         */
        post: operations["revert_config_api_config_revert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restart
         * @description Restart the application.
         */
        post: operations["restart_api_restart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduler/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scheduler Status
         * @description Get scheduler status.
         */
        get: operations["get_scheduler_status_api_scheduler_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduler/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause Scheduler
         * @description Pause automatic updates.
         */
        post: operations["pause_scheduler_api_scheduler_pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduler/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume Scheduler
         * @description Resume automatic updates.
         */
        post: operations["resume_scheduler_api_scheduler_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Info
         * @description Get system information (CPU, memory, disk, temperature).
         */
        get: operations["get_info_api_system_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Logs
         * @description Get system logs.
         */
        get: operations["get_logs_api_system_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/logs/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Logs
         * @description Export system logs as text file.
         */
        get: operations["export_logs_api_system_logs_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/display/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current
         * @description Get current display information.
         */
        get: operations["get_current_api_display_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/display/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Preview
         * @description Serve the current display preview image.
         */
        get: operations["get_preview_api_display_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/display/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get History
         * @description Get display history.
         */
        get: operations["get_history_api_display_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/display/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health
         * @description Get e-ink display health metrics.
         */
        get: operations["get_health_api_display_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Plugins
         * @description Get list of all available plugins.
         */
        get: operations["list_plugins_api_plugins_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Instances
         * @description Get list of all plugin instances.
         */
        get: operations["list_instances_api_plugins_instances_get"];
        put?: never;
        /**
         * Create Instance
         * @description Create a new plugin instance.
         */
        post: operations["create_instance_api_plugins_instances_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/instances/{instance_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Instance
         * @description Get details for a specific instance.
         */
        get: operations["get_instance_api_plugins_instances__instance_id__get"];
        /**
         * Update Instance
         * @description Update an instance.
         */
        put: operations["update_instance_api_plugins_instances__instance_id__put"];
        post?: never;
        /**
         * Delete Instance
         * @description Delete an instance.
         */
        delete: operations["delete_instance_api_plugins_instances__instance_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/instances/{instance_id}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enable Instance
         * @description Enable an instance.
         */
        post: operations["enable_instance_api_plugins_instances__instance_id__enable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/instances/{instance_id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Disable Instance
         * @description Disable an instance.
         */
        post: operations["disable_instance_api_plugins_instances__instance_id__disable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/instances/{instance_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Instance
         * @description Test run a plugin instance.
         */
        post: operations["test_instance_api_plugins_instances__instance_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/{plugin_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Plugin
         * @description Get details for a specific plugin.
         */
        get: operations["get_plugin_api_plugins__plugin_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Schedules
         * @description Get all schedule slots.
         */
        get: operations["list_schedules_api_schedules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules/slot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Slot
         * @description Set a single time slot.
         */
        post: operations["set_slot_api_schedules_slot_post"];
        /**
         * Clear Slot
         * @description Clear a single time slot.
         */
        delete: operations["clear_slot_api_schedules_slot_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules/slots/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Set Slots
         * @description Set multiple slots at once.
         */
        post: operations["bulk_set_slots_api_schedules_slots_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current Schedule
         * @description Get what's currently scheduled for right now.
         */
        get: operations["get_current_schedule_api_schedules_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clear All Schedules
         * @description Clear all schedule slots.
         */
        post: operations["clear_all_schedules_api_schedules_clear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Index
         * @description Serve SPA for root route.
         */
        get: operations["index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plugins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Plugins Page
         * @description Serve SPA for plugins page.
         */
        get: operations["plugins_page_plugins_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Schedule Page
         * @description Serve SPA for schedule page.
         */
        get: operations["schedule_page_schedule_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * System Page
         * @description Serve SPA for system page.
         */
        get: operations["system_page_system_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Config Page
         * @description Serve SPA for config page.
         */
        get: operations["config_page_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favicon.svg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve Favicon
         * @description Serve the favicon.
         */
        get: operations["serve_favicon_favicon_svg_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve Assets
         * @description Serve built assets from dist directory.
         */
        get: operations["serve_assets_assets__filename__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * APIResponse
         * @description Base API response wrapper.
         */
        APIResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            /** Error */
            error?: string | null;
        };
        /**
         * APIResponseWithData
         * @description API response with generic data field.
         */
        APIResponseWithData: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            /** Error */
            error?: string | null;
            /** Data */
            data?: unknown | null;
        };
        /**
         * BulkSlotSetRequest
         * @description Request body for bulk setting slots.
         */
        BulkSlotSetRequest: {
            /** Slots */
            slots: components["schemas"]["SlotSetRequest"][];
        };
        /**
         * DisplayCurrentData
         * @description Current display information.
         */
        DisplayCurrentData: {
            /** Image Id */
            image_id?: string | null;
            /** Last Update */
            last_update?: string | null;
            /**
             * Plugin Name
             * @default Unknown
             */
            plugin_name: string;
            /**
             * Instance Name
             * @default Unknown
             */
            instance_name: string;
            /** Status */
            status: string;
            /** Has Preview */
            has_preview: boolean;
            /**
             * Display Count
             * @default 0
             */
            display_count: number;
        };
        /**
         * DisplayCurrentResponse
         * @description Response for /api/display/current endpoint.
         */
        DisplayCurrentResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            /** Error */
            error?: string | null;
            data?: components["schemas"]["DisplayCurrentData"] | null;
        };
        /**
         * DisplayHealthData
         * @description Display health metrics.
         */
        DisplayHealthData: {
            /**
             * Refresh Count
             * @default 0
             */
            refresh_count: number;
            /** Last Refresh */
            last_refresh?: string | null;
            /** Status */
            status: string;
            /**
             * Error Count
             * @default 0
             */
            error_count: number;
        };
        /**
         * DisplayHealthResponse
         * @description Response for /api/display/health endpoint.
         */
        DisplayHealthResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            /** Error */
            error?: string | null;
            data?: components["schemas"]["DisplayHealthData"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InstanceCreateRequest
         * @description Request body for creating a plugin instance.
         */
        InstanceCreateRequest: {
            /** Plugin Id */
            plugin_id: string;
            /** Name */
            name: string;
            /** Settings */
            settings?: {
                [key: string]: unknown;
            };
        };
        /**
         * InstanceData
         * @description Plugin instance data.
         */
        InstanceData: {
            /** Id */
            id: string;
            /** Plugin Id */
            plugin_id: string;
            /** Name */
            name: string;
            /** Settings */
            settings?: {
                [key: string]: unknown;
            };
            /** Enabled */
            enabled: boolean;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /**
         * InstanceResponse
         * @description Response for /api/plugins/instances/<id> endpoint.
         */
        InstanceResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            /** Error */
            error?: string | null;
            data?: components["schemas"]["InstanceData"] | null;
        };
        /**
         * InstanceUpdateRequest
         * @description Request body for updating a plugin instance.
         */
        InstanceUpdateRequest: {
            /** Name */
            name?: string | null;
            /** Settings */
            settings?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * InstancesListResponse
         * @description Response for /api/plugins/instances endpoint.
         */
        InstancesListResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            /** Error */
            error?: string | null;
            /** Data */
            data?: components["schemas"]["InstanceData"][] | null;
        };
        /**
         * LogEntry
         * @description Log entry data.
         */
        LogEntry: {
            /** Timestamp */
            timestamp: string;
            /** Level */
            level: string;
            /** Message */
            message: string;
        };
        /**
         * PluginData
         * @description Plugin metadata.
         */
        PluginData: {
            /** Id */
            id: string;
            /** Display Name */
            display_name: string;
            /** Class Name */
            class_name: string;
            /** Description */
            description: string;
            /** Author */
            author: string;
            /** Version */
            version: string;
            /** Icon */
            icon?: string | null;
            settings_schema?: components["schemas"]["SettingsSchema"] | null;
        };
        /**
         * PluginResponse
         * @description Response for /api/plugins/<id> endpoint.
         */
        PluginResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            /** Error */
            error?: string | null;
            data?: components["schemas"]["PluginData"] | null;
        };
        /**
         * PluginsListResponse
         * @description Response for /api/plugins endpoint.
         */
        PluginsListResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            /** Error */
            error?: string | null;
            /** Data */
            data?: components["schemas"]["PluginData"][] | null;
        };
        /**
         * ScheduleCurrentData
         * @description Current schedule information.
         */
        ScheduleCurrentData: {
            /** Has Content */
            has_content: boolean;
            /**
             * Source Type
             * @default none
             */
            source_type: string;
            /** Target Type */
            target_type?: string | null;
            /** Target Id */
            target_id?: string | null;
            /** Target Name */
            target_name?: string | null;
            /** Instance */
            instance?: {
                [key: string]: unknown;
            } | null;
            /** Day */
            day?: number | null;
            /** Hour */
            hour?: number | null;
        };
        /**
         * ScheduleCurrentResponse
         * @description Response for /api/schedules/current endpoint.
         */
        ScheduleCurrentResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            /** Error */
            error?: string | null;
            data?: components["schemas"]["ScheduleCurrentData"] | null;
        };
        /**
         * SchedulerStatus
         * @description Scheduler status information.
         */
        SchedulerStatus: {
            /** Paused */
            paused: boolean;
            /** Next Update */
            next_update?: string | null;
            /** Last Update */
            last_update?: string | null;
            /** Current Time */
            current_time?: string | null;
            /** Timezone */
            timezone?: string | null;
            /** Update Time */
            update_time?: string | null;
        };
        /**
         * SchedulerStatusResponse
         * @description Response for /api/scheduler/status endpoint.
         */
        SchedulerStatusResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            /** Error */
            error?: string | null;
            data?: components["schemas"]["SchedulerStatus"] | null;
            status?: components["schemas"]["SchedulerStatus"] | null;
        };
        /**
         * SettingsField
         * @description Schema for a single settings field.
         */
        SettingsField: {
            /** Key */
            key: string;
            /** Type */
            type: string;
            /** Label */
            label: string;
            /** Description */
            description?: string | null;
            /** Help */
            help?: string | null;
            /**
             * Required
             * @default false
             */
            required: boolean;
            /** Default */
            default?: unknown | null;
            /** Options */
            options?: {
                [key: string]: unknown;
            }[] | null;
            /** Min */
            min?: number | null;
            /** Max */
            max?: number | null;
            /** Placeholder */
            placeholder?: string | null;
        };
        /**
         * SettingsSchema
         * @description Schema for plugin settings with sections.
         */
        SettingsSchema: {
            /** Sections */
            sections?: components["schemas"]["SettingsSection"][];
        };
        /**
         * SettingsSection
         * @description Schema for a settings section containing fields.
         */
        SettingsSection: {
            /** Title */
            title: string;
            /** Fields */
            fields?: components["schemas"]["SettingsField"][];
        };
        /**
         * SlotClearRequest
         * @description Request body for clearing a slot.
         */
        SlotClearRequest: {
            /** Day */
            day?: number | null;
            /** Hour */
            hour?: number | null;
        };
        /**
         * SlotSetRequest
         * @description Request body for setting a schedule slot.
         */
        SlotSetRequest: {
            /** Day */
            day: number;
            /** Hour */
            hour: number;
            /**
             * Target Type
             * @default instance
             */
            target_type: string;
            /** Target Id */
            target_id: string;
        };
        /**
         * SlotSetResponse
         * @description Response for setting a slot.
         */
        SlotSetResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            /** Error */
            error?: string | null;
            /** Slot */
            slot?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * SystemInfoData
         * @description System information data.
         */
        SystemInfoData: {
            /** Cpu Percent */
            cpu_percent: number;
            /** Memory Percent */
            memory_percent: number;
            /** Disk Percent */
            disk_percent: number;
            /** Temperature */
            temperature?: number | null;
            /** Uptime */
            uptime: string;
            /** Platform */
            platform: string;
        };
        /**
         * SystemInfoResponse
         * @description Response for /api/system/info endpoint.
         */
        SystemInfoResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            /** Error */
            error?: string | null;
            data?: components["schemas"]["SystemInfoData"] | null;
        };
        /**
         * SystemLogsResponse
         * @description Response for /api/system/logs endpoint.
         */
        SystemLogsResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            /** Error */
            error?: string | null;
            /** Data */
            data?: components["schemas"]["LogEntry"][] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponseWithData"];
                };
            };
        };
    };
    test_connections_api_connections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponseWithData"];
                };
            };
        };
    };
    trigger_update_api_update_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse"];
                };
            };
        };
    };
    clear_display_api_clear_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse"];
                };
            };
        };
    };
    get_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponseWithData"];
                };
            };
        };
    };
    update_config_api_config_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_config_api_config_save_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponseWithData"];
                };
            };
        };
    };
    revert_config_api_config_revert_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse"];
                };
            };
        };
    };
    restart_api_restart_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse"];
                };
            };
        };
    };
    get_scheduler_status_api_scheduler_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulerStatusResponse"];
                };
            };
        };
    };
    pause_scheduler_api_scheduler_pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulerStatusResponse"];
                };
            };
        };
    };
    resume_scheduler_api_scheduler_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulerStatusResponse"];
                };
            };
        };
    };
    get_info_api_system_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfoResponse"];
                };
            };
        };
    };
    get_logs_api_system_logs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemLogsResponse"];
                };
            };
        };
    };
    export_logs_api_system_logs_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_current_api_display_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisplayCurrentResponse"];
                };
            };
        };
    };
    get_preview_api_display_preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_history_api_display_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponseWithData"];
                };
            };
        };
    };
    get_health_api_display_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisplayHealthResponse"];
                };
            };
        };
    };
    list_plugins_api_plugins_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginsListResponse"];
                };
            };
        };
    };
    list_instances_api_plugins_instances_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstancesListResponse"];
                };
            };
        };
    };
    create_instance_api_plugins_instances_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstanceCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_instance_api_plugins_instances__instance_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_instance_api_plugins_instances__instance_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstanceUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_instance_api_plugins_instances__instance_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enable_instance_api_plugins_instances__instance_id__enable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disable_instance_api_plugins_instances__instance_id__disable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_instance_api_plugins_instances__instance_id__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plugin_api_plugins__plugin_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plugin_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_schedules_api_schedules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponseWithData"];
                };
            };
        };
    };
    set_slot_api_schedules_slot_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SlotSetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotSetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_slot_api_schedules_slot_delete: {
        parameters: {
            query?: {
                day?: number | null;
                hour?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SlotClearRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponseWithData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_set_slots_api_schedules_slots_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkSlotSetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponseWithData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_schedule_api_schedules_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleCurrentResponse"];
                };
            };
        };
    };
    clear_all_schedules_api_schedules_clear_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponseWithData"];
                };
            };
        };
    };
    index__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    plugins_page_plugins_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    schedule_page_schedule_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    system_page_system_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    config_page_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    serve_favicon_favicon_svg_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    serve_assets_assets__filename__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
